name: Unit Tests Analyses

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Unit tests
        run: npm run test:unit
      - name: Generate Coverage Report
        run: npm run coverage
      - name: Upload coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage
