services:
  test-frontend:
    build:
      context: ./
    ports:
      - "5173:80"
    environment:
      VITE_WEBANK_OBS_URL: 'http://localhost:8081'
      VITE_WEBANK_PRS_URL: 'http://localhost:8080'