name: Epic
description: A large feature that is broken down into multiple linked issues.
labels: ["kind/epic", "status/triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature at a high-level.
    validations:
      required: true
  - type: input
    id: discussion
    attributes:
      label: Discussion
      description: |
        Provide a link to the GitHub Discussion for the feature.
    validations:
      required: true
  - type: textarea
    id: issues
    attributes:
      label: Issues
      description: List the issues related to this epic.
      placeholder: |
        - #1
        - #2
    validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Provide a brief explanation of why the feature should be added.
    validations:
      required: false