name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache@v3
        id: node-cache
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run build