name: Lint Analyses

on:
  workflow_run:
    workflows:
      - Main Workflow
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: ESLint
        run: npm run lint:check
