name: Main Workflow

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Build
        run: npm run build

  lint:
    needs: install
    uses: ./.github/workflows/analyses/linting.yml

  prettier:
    needs: install
    uses: ./.github/workflows/analyses/prettier.yml

  typescript:
    needs: install
    uses: ./.github/workflows/analyses/typescript.yml

  unit_tests:
    needs: install
    uses: ./.github/workflows/analyses/tests.yml

  sonarqube:
    needs: [build, unit_tests]
    uses: ./.github/workflows/analyses/sonarqube.yml
