name: Prettier Analyses

on:
  workflow_run:
    workflows:
      - Main Workflow
    types:
      - completed

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cached node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ github.sha }}
      - name: Prettier
        run: npm run prettier:check
